networks:
  dev:



services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - beckend
      - frontend
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - dev


  beckend:
    build:
      context: ./beck
    networks:
      - dev

  frontend:
    build:
      context: ./project-bathhouse
    networks:
      - dev
