
user               root;
worker_processes   1;

http {
    server {
        listen  80

        server_name  http://90.156.156.114;

        location / {
            proxy_pass http://frontent:3030/;
        }

        location /api {
            proxy_pass http://beckend:8080/;
        }
    }
}

